# -*- coding: utf-8 -*-
"""Task4A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VPN0ugYaMMrFsi8SPYUFhq2kAmAlIUA0

Task 4A - 7 favori şehrin dataFrame tablosu oluşturulması.
"""

import pandas as pd
import numpy as np

population = {'Eskişehir': 	898369,
                   'İzmir': 4425789,
                   'İstanbul': 15840900,
                   'Muğla': 1021141, 
                   'Antalya': 2619832 , 
                   'Balıkesir': 1250610 ,
                   'Bursa' : 3147818 }
population = pd.Series(population)
population

area = {'Eskişehir': 	13960,
                   'İzmir': 11891,
                   'İstanbul': 5461,
                   'Muğla': 12654, 
                   'Antalya': 20177 , 
                   'Balıkesir': 14583 ,
                   'Bursa' : 10813 }
area = pd.Series(area)
area

sehirler = pd.DataFrame({'population': population,
                         'area(km2)': area})
sehirler